Bind exec opts to alias name

diff --git a/devcontainer b/devcontainer
--- a/devcontainer
+++ b/devcontainer
@@ -6,12 +6,13 @@ err() {
 
 printhelp() {
 	err "Usage: . $(basename $1) [OPTION]... IMG"
+	err "Usage: . $(basename $1) -C [OPTION]... CONT"
 	err "Start docker container with current dir mounted and user mirrored"
 	err
 	err "Options:"
-	err "  -n CONTAINER           name of container [ generated by docker by default ]"
-	err "  -w WORKSPACE           workspace directory name inside of container [ CWD by default ]"
+	err "  -C                     create an alias for existing container instead of starting one"
 	err "  -r ARG                 extra arg to be passed to 'docker run'"
+	err "  -w WORKSPACE           workspace directory name inside of container [ CWD by default ]"
 	err "  -e ARG                 extra arg to be passed to 'docker exec'"
 	err "  -a NAME                alias name to quick getting into container [ \"dr\" by default ]"
 }
@@ -21,14 +22,13 @@ if [ $BASH_SOURCE = $0 ]; then
 	exit 1
 fi
 
-__dc_run() {
-	docker exec -i \
-		$__DC_ARGS \
-		sh -lc "$*"
-}
 
 defalias() {
-	eval "$1() { __dc_run \$@; }"
+	local name=$1
+	shift
+	eval "$name() {
+		docker exec -i $* sh -lc \"\$*\"
+	}"
 }
 
 main() {
@@ -38,75 +38,78 @@ main() {
 
 	local workspace=/p
 	local alias=dr
+	local is_container=false
 
 	local run_args=""
-	__DC_ARGS=""
-	while getopts n:r:e:w:k:a: opt; do
+	local exec_args=""
+	while getopts Cr:w:e:a: opt; do
 		case $opt in
-		r) 
+		C)
+			is_container=true
+			;;
+		r)
 			run_args="$run_args $OPTARG"
 			;;
-		n) 
-			local cname="$OPTARG"
+		w)
+			local workspace="$OPTARG"
 			;;
-		w) 
-			local workspace="$OPTARG" 
+		e)
+			exec_args="$exec_args $OPTARG"
 			;;
-		e) 
-			__DC_ARGS="$__DC_ARGS $OPTARG"
-			;;
-		a)	
+		a)
 			local alias="$OPTARG"
 			;;
 		esac
 	done
 	shift $((OPTIND - 1))
+	local target="$1"
 
-	if [ -t 0 ]; then
-		__DC_ARGS=" $__DC_ARGS -t"
-	fi
-
-	if [ "$cname" ] && [ $(docker ps -aqf "name=$cname") ]; then
-		__DC_ARGS="$__DC_ARGS -u user $cname"
-		__dc_run true
-		if [ $? != 0 ]; then
-			err "Container \"$cname\" presents but cannot be used"
-			return 1
-		fi
-		defalias $alias
-		return 0
-	fi
-
-	local dockerimage="$1"
-	if ! [ "$dockerimage" ]; then
-		err "No image name provided"
+	if ! [ "$target" ]; then
+		err "No image or container provided"
 		err
 		printhelp $BASH_SOURCE
 		return 1
 	fi
 
-	local cont # don't eat exit code
-	cont=$(docker run -d \
-		$run_args \
-		${cname:+--name "$cname"} \
-		-e "WORKSPACE=$workspace" \
-		-v "$PWD:$workspace" \
-		--entrypoint /bin/sh \
-		$dockerimage \
-		-c 'while :; do sleep 3600; done')
-
-	if [ $? != 0 ] && [ $cont ]; then
-		docker rm $cont >/dev/null
-		return 1
+	if [ -t 0 ]; then
+		exec_args=" $exec_args -t"
 	fi
 
-	docker cp $(dirname $BASH_SOURCE)/container/. $cont:/.
-	__DC_ARGS="$__DC_ARGS $cont"
-	__dc_run /usr/local/sbin/init.sh
-	__DC_ARGS="-u user $__DC_ARGS"
+	if [ "$is_container" = true ]; then
+		if [ "$run_args" != "" ]; then
+			err "docker run arguments ignored with -C:$run_args"
+		fi
 
-	defalias $alias
-	echo $cont
+		defalias $alias $exec_args -u user $target
+		$alias true
+		if [ $? != 0 ]; then
+			err "Can not use container \"$target\""
+			unset $alias
+			return 1
+		fi
+		echo $target
+	else
+		local cont # don't eat exit code
+		cont=$(docker run -d \
+			$run_args \
+			-e "WORKSPACE=$workspace" \
+			-v "$PWD:$workspace" \
+			--entrypoint /bin/sh \
+			$target \
+			-c 'while :; do sleep 3600; done')
+
+		if [ $? != 0 ] && [ $cont ]; then
+			docker rm $cont >/dev/null
+			return 1
+		fi
+
+		docker cp $(dirname $BASH_SOURCE)/container/. $cont:/.
+		docker exec $exec_args $cont /usr/local/sbin/init.sh
+
+		defalias $alias $exec_args -u user $cont
+		echo $cont
+	fi
+
 }
 
 bootstrap() {
